export const CarListingDataSource = [
  {
    id: 1,
    RegNo: '1224433-abc-jjs',
    Model: 'Civic 1992',
    Category: 'Honda',
    Color: 'white',
    imgae: require('../assets/images/trending/mercedes.png'),
  },
  {
    id: 2,
    RegNo: '12-7893-88339',
    Model: 'City 1994',
    Category: 'Honda',
    Color: 'red',
    imgae: require('../assets/images/trending/togg.png'),
  },
  {
    id: 3,
    RegNo: '1224433323232',
    Model: 'Corola 2002',
    Category: 'Toyota',
    Color: 'red',
    imgae: require('../assets/images/trending/prosche.png'),
  },
  {
    id: 4,
    RegNo: '1224433',
    Model: '1992',
    Category: 'Honda',
    Color: 'red',
    imgae: require('../assets/images/trending/bmw.png'),
  },
  {
    id: 5,
    RegNo: '1224433',
    Model: '1992',
    Category: 'Honda',
    Color: 'red',
    imgae: require('../assets/images/trending/bmw.png'),
  },
  {
    id: 6,
    RegNo: '1224433',
    Model: '1992',
    Category: 'Honda',
    Color: 'red',
    imgae: require('../assets/images/trending/bmw.png'),
  },
  {
    id: 7,
    RegNo: '1224433',
    Model: '1992',
    Category: 'Honda',
    Color: 'red',
    imgae: require('../assets/images/trending/bmw.png'),
  },
  {
    id: 8,
    RegNo: '1224433',
    Model: '1992',
    Category: 'Honda',
    Color: 'red',
    imgae: require('../assets/images/trending/bmw.png'),
  },
];
